apiVersion: v1
kind: Service
metadata:
  name: task-10.1p
spec:
  selector:
    tier: frontend
  clusterIP: 10.99.132.220
  externalTrafficPolicy: Cluster
  ports:
  - name: myport
    port: 8037
    protocol: TCP
    targetPort: 3030
  type: LoadBalancer


  