apiVersion: v1
kind: Pod
metadata:
  name: mypod
  labels:
    tier: frontend
spec:
  containers:
  - image: seoheelee/sit737-10.1p
    name: my-node-app
    ports:
    - containerPort: 3030
  dnsPolicy: ClusterFirst
  restartPolicy: Always