version: '3'
services:
  my-node-app:
    platform: 
    image: seoheelee/sit737-10.1p
    ports:
      - "8037:3030"
    environment:
      - PORT=8037
    deploy:
      replicas: 3
    labels:
      - "tier=frontend"
